### ISSUE TITLE
drift in one direction

### ISSUE THREAD

**Issue by fabolhak** [tum-phoenix/drive_ros_imu_odo_odometry#6]
there seems to be a drift in one direction:
![screenshot_2017-11-25_19-34-28](https://user-images.githubusercontent.com/20029691/33233542-c41caa2e-d217-11e7-96ea-187b74c31054.png)

**Comment by DavidHan008** [comment]
I see same

**Comment by fabolhak** [comment]
should be fixed with: https://github.com/tum-phoenix/drive_ros_imu_filter

Or better parameter tuning can help.
